model:
  arch: minigpt_v2
  model_type: pretrain
  max_txt_len: 160
  end_sym: '###'
  prompt_path: prompts/alignment.txt
  prompt_template: '###Human: {} ###Assistant: '
  llama_model: /data/kiriti/MiniGPT-4/llama_weights/Llama-2-7b-chat-hf
  use_grad_checkpoint: true
  lora_r: 16
  lora_alpha: 16

paths:
  library_root: /data/kiriti/MiniGPT-4

datasets:
  llava_conversation:
    data_type: images
    build_info:
      image_path: /data/kiriti/MiniGPT-4/plant_diagnostic
      ann_paths:
        train: /data/kiriti/MiniGPT-4/plant_diagnostic/datasets/strawberry_stage2_train.json
        val:   /data/kiriti/MiniGPT-4/plant_diagnostic/datasets/strawberry_stage2_val.json
    batch_size: 1
    vis_processor:
      train: { name: blip2_image_train, image_size: 336 }
      val:   { name: blip2_image_eval,  image_size: 336 }
      eval:  { name: blip2_image_eval,  image_size: 336 }
    text_processor:
      train: { name: blip_caption }
      val:   { name: blip_caption }

run:
  task: image_text_pretrain
  lr_sched: linear_warmup_cosine_lr
  init_lr: 1e-5
  min_lr: 5e-6
  warmup_lr: 1e-6
  warmup_steps: 96
  weight_decay: 0.05
  max_grad_norm: 1.0
  max_epoch: 3
  num_workers: 0
  accumulation_steps: 4
  amp: true
  resume_ckpt_path: null
  evaluate: true
  train_splits: ["train"]
  val_splits: ["val"]
  device: cuda
  world_size: 1
  dist_url: env://
  distributed: true
  wandb_log: false
  output_dir: output/minigpt4_stage2_finetune
  seed: 42

