model:
  arch: minigpt_v2
  model_type: pretrain
  max_txt_len: 160
  end_sym: "</s>"
  llama_model: "/data/kiriti/MiniGPT-4/llama_weights/Llama-2-7b-chat-hf"
  ckpt: ""
  use_grad_checkpoint: true
  low_resource: true
  chat_template: true
  lora_r: 16
  lora_alpha: 32
  lora_dropout: 0.05

datasets:
  llava_conversation:
    data_type: images
    build_info:
      annotations:
        train:
          storage: "/data/kiriti/MiniGPT-4/plant_diagnostic/datasets/strawberry_stage2.json"
        val:
          storage: "/data/kiriti/MiniGPT-4/plant_diagnostic/datasets/holdout_val_list.json"
      images:
        train: "/data/kiriti/MiniGPT-4/plant_diagnostic/data/train"
        val:   "/data/kiriti/MiniGPT-4/plant_diagnostic/data"
    vis_processor:
      train: { name: "blip2_image_train", image_size: 448 }
      eval:  { name: "blip2_image_eval",  image_size: 448 }
    text_processor:
      train: { name: "blip_caption" }
      eval:  { name: "blip_caption" }
    batch_size: 2



run:
  task: image_text_pretrain
  output_dir: "/data/kiriti/MiniGPT-4/output/minigptv2_finetune"

  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 3e-5
  min_lr: 1e-5
  warmup_lr: 1e-6
  warmup_steps_ratio: 0.05
  iters_per_epoch: 1500
  weight_decay: 0.05
  max_epoch: 10
  num_workers: 4
  seed: 42

  # Per-GPU batch; 2 GPUs × 2 batch × 8 accum = effective 32
  batch_size_train: 2
  accumulation_steps: 8
  amp: true
  max_grad_norm: 1.0

  # Dist settings — keep simple; torchrun sets ranks/world size
  distributed: true
  dist_url: "env://"
  device: "cuda"

  # Logging / ckpt
  wandb_log: true
  job_name: "minigptv2_finetune_strawberry"
  resume_ckpt_path: null
  evaluate: false
  train_splits: ["train"]
  val_splits: ["val"]

